{
 "title": "Principal Nuevo",
 "time": { "from": "2023-12-31T01:38:06.379Z", "to": "2025-03-03T12:05:23.290Z" },
 "templating": {
  "list": [
   {
    "name": "Oficina",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Número de oficinas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT COUNT(DISTINCT Oficina)  AS oficinas_activas\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE Oficina IN UNNEST([${Oficina}])"
    }
   ]
  },
  {
   "title": "Número de modelos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT COUNT(DISTINCT Model_id) AS modelos_activos\r\nFROM `tfm-nttdata.NTTData.metricas`\r\n"
    }
   ]
  },
  {
   "title": "Desglose de la energia gastada por mes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 6, "y": 0 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  TIMESTAMP(DATE_TRUNC(Execution_day, MONTH)) AS time,\r\n  SUM(Total_inference_energy_wh) / 1000 AS Energia_total_kWh\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE Execution_day IS NOT NULL\r\n  AND Oficina IN UNNEST([${Oficina}])\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time\r\n"
    }
   ]
  },
  {
   "title": "Energia utilizada",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT SUM(EPT_kwh)\r\nFROM `tfm-nttdata.NTTData.metricas` \r\nWHERE Execution_day IS NOT NULL\r\n  AND Oficina IN UNNEST([${Oficina}])"
    }
   ]
  },
  {
   "title": "Distribución de oficinas",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Oficina,\r\n  DENSE_RANK() OVER (ORDER BY Oficina) AS oficina_id,\r\n  AVG(Latitud) AS latitude,\r\n  AVG(Longitud) AS longitude\r\nFROM\r\n  `tfm-nttdata.NTTData.metricas`\r\nWHERE\r\n  Latitud IS NOT NULL\r\n  AND Longitud IS NOT NULL\r\nGROUP BY\r\n  Oficina\r\n"
    }
   ]
  },
  {
   "title": "Emisiones de CO2 totales",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "CO2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT SUM(CPT_kg_co2)\r\nFROM `tfm-nttdata.NTTData.metricas` \r\nWHERE Oficina IN UNNEST([${Oficina}])"
    }
   ]
  },
  {
   "title": "Consumo de CO2 por mes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  TIMESTAMP(DATE_TRUNC(Execution_day, MONTH)) AS time,\r\n  SUM(CPT_kg_co2) AS Total_CO2\r\nFROM\r\n  `tfm-nttdata.NTTData.metricas`\r\nWHERE Execution_day IS NOT NULL\r\n  AND Oficina IN UNNEST([${Oficina}])\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time\r\n"
    }
   ]
  },
  {
   "title": "Precisión por KG de CO2 emitido",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  TIMESTAMP(DATE_TRUNC(Execution_day, MONTH)) AS time,\r\n  ROUND(AVG(Carbon_efficiency), 2) AS porcentaje_no_usado\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE Execution_day IS NOT NULL\r\n  AND Carbon_efficiency IS NOT NULL\r\n  AND Oficina IN UNNEST([${Oficina}])\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Porcentaje de datos no usados ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  TIMESTAMP(DATE_TRUNC(Execution_day, MONTH)) AS time,\r\n  ROUND(AVG(Data_Waste_Ratio) * 100, 2) AS porcentaje_no_usado\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE Execution_day IS NOT NULL\r\n  AND Data_Waste_Ratio IS NOT NULL\r\n  AND Oficina IN UNNEST([${Oficina}])\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Media de MFS ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  TIMESTAMP(DATE_TRUNC(Execution_day, MONTH)) AS time,\r\n  ROUND(AVG(Model_Footprint_Score), 2) AS model_footprint_score\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE Execution_day IS NOT NULL\r\n  AND Model_Footprint_Score IS NOT NULL\r\n  AND Model_accuracy < 1\r\n  AND Oficina IN UNNEST([${Oficina}])\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Energia usada para una prediccioón",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Wh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  TIMESTAMP(DATE_TRUNC(Execution_day, MONTH)) AS time,\r\n  ROUND(AVG(Epp_Wh), 2) AS porcentaje_no_usado\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE Execution_day IS NOT NULL\r\n  AND Epp_Wh IS NOT NULL\r\n  AND Oficina IN UNNEST([${Oficina}])\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  }
 ]
}