{
 "title": "CPT interior",
 "time": { "from": "2024-01-01T00:00:00.000Z", "to": "2025-03-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Emision Media por Modelo",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Model_id,\r\n  ROUND(AVG(CPT_kg_co2), 4) AS Emision_media_co2\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE CPT_kg_co2 IS NOT NULL\r\nGROUP BY Model_id\r\nORDER BY Emision_media_co2 DESC\r\n"
    }
   ]
  },
  {
   "title": "Media de emisiones por ejecucion en cada oficina",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Oficina,\r\n  ROUND(AVG(CPT_kg_co2), 4) AS Emision_media_co2\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE\r\n  CPT_kg_co2 IS NOT NULL\r\n  AND TRIM(Oficina) IS NOT NULL\r\n  AND TRIM(Oficina) != ''\r\nGROUP BY Oficina\r\nORDER BY Emision_media_co2 DESC\r\n"
    }
   ]
  },
  {
   "title": "Emisiones por tiempo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 10 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  TIMESTAMP(DATE_TRUNC(Execution_day, MONTH)) AS time,\r\n  Oficina AS metric,\r\n  ROUND(AVG(CPT_kg_co2), 4) AS value\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE\r\n  Execution_day IS NOT NULL\r\n  AND CPT_kg_co2 IS NOT NULL\r\n  AND TRIM(Oficina) != ''\r\n  AND LOWER(TRIM(Oficina)) != 'desconocido'\r\nGROUP BY time, Oficina\r\nORDER BY time, Oficina\r\n"
    }
   ]
  },
  {
   "title": "CO2 por oficina",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Oficina,\r\n  ROUND(SUM(CPT_kg_co2), 2) AS Emision_total_co2\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE\r\n  CPT_kg_co2 IS NOT NULL\r\n  AND TRIM(Oficina) IS NOT NULL\r\n  AND TRIM(Oficina) != ''\r\nGROUP BY Oficina\r\nORDER BY Emision_total_co2 DESC\r\n"
    }
   ]
  }
 ]
}