{
 "title": "DWR interior",
 "time": { "from": "2024-01-01T00:00:00.000Z", "to": "2025-03-01T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Oficina",
    "query": {}
   },
   {
    "name": "Modelo",
    "label": "Modelo",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DWR por modelo",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Model_id,\r\n  ROUND(AVG(Data_Waste_Ratio), 4) AS DWR\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE Data_Waste_Ratio IS NOT NULL\r\n  AND  Oficina IN UNNEST([${Oficina}])\r\nGROUP BY Model_id\r\nORDER BY DWR DESC\r\n\r\n"
    }
   ]
  },
  {
   "title": "DWR por oficina",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Oficina,\r\n  AVG(Data_Waste_Ratio) AS DWR\r\nFROM \r\n  `tfm-nttdata.NTTData.metricas`\r\nWHERE\r\n  Model_id IN UNNEST([${Modelo:csv}])\r\nGROUP BY\r\n  Oficina\r\nORDER BY\r\n  DWR DESC\r\n"
    }
   ]
  },
  {
   "title": "DWR en el tiempo",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  TIMESTAMP(DATE_TRUNC(Execution_day, MONTH)) AS time,\r\n  ROUND(AVG(Data_Waste_Ratio) * 100, 2) AS porcentaje_no_usado\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE Execution_day IS NOT NULL\r\n  AND Data_Waste_Ratio IS NOT NULL\r\n  AND Oficina IN UNNEST([${Oficina}])\r\n  AND Model_id IN UNNEST([${Modelo:csv}])\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  }
 ]
}