{
 "title": "EPP y total predicciones",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Predicciones por Oficina",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Oficina,\r\n  SUM(num_predictions) AS Total_predicciones\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE TRIM(Oficina) != ''\r\nGROUP BY Oficina\r\nORDER BY Total_predicciones DESC\r\n"
    }
   ]
  },
  {
   "title": "Predicción por modelo",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 15, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  CAST(Model_id AS STRING) AS Modelo,\r\n  SUM(num_predictions) AS Total_predicciones\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nGROUP BY Modelo\r\nORDER BY Total_predicciones DESC\r\n"
    }
   ]
  },
  {
   "title": "EPP media por ciudad",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Oficina,\r\n  ROUND(AVG(Epp_wh), 4) AS Epp_medio_wh\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE TRIM(Oficina) != '' AND Epp_wh IS NOT NULL\r\nGROUP BY Oficina\r\nORDER BY Epp_medio_wh DESC\r\n"
    }
   ]
  },
  {
   "title": "EPP por modelo",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 14, "x": 8, "y": 10 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  CAST(Model_id AS STRING) AS Modelo,\r\n  ROUND(AVG(Epp_wh), 4) AS Epp_medio_wh\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE Epp_wh IS NOT NULL\r\nGROUP BY Modelo\r\nORDER BY Epp_medio_wh DESC\r\n"
    }
   ]
  }
 ]
}