{
 "title": "EPT_interior",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Oficina",
    "label": "Oficina",
    "query": {}
   },
   {
    "name": "Modelo",
    "label": "Modelo",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "EPT ",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Model_id,\r\n  ROUND(SUM(EPT_kwh), 4) AS EPT_Total_kWh\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE EPT_kwh IS NOT NULL \r\n      AND Oficina IN UNNEST([${Oficina}])\r\nGROUP BY Model_id\r\nORDER BY EPT_Total_kWh DESC "
    }
   ]
  },
  {
   "title": "Modelos con mayor gasto en energia por tamaño",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  CAST(Model_id AS STRING) AS Modelos,\r\n  ROUND(EPT_per_mb, 4) AS Eficiencia_energetica_por_modelo\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE EPT_per_mb IS NOT NULL\r\n  AND Oficina IN UNNEST([${Oficina}])\r\nORDER BY Eficiencia_energetica_por_modelo DESC\r\nLIMIT 5\r\n"
    }
   ]
  },
  {
   "title": "EPT Media por oficina",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 5, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Oficina,\r\n  SUM(EPT_kwh) AS media_ept\r\nFROM\r\n  `tfm-nttdata.NTTData.metricas`\r\nWHERE \r\n  Model_id IN UNNEST([${Modelo:csv}])\r\nGROUP BY\r\n  Oficina\r\nORDER BY\r\n  media_ept DESC\r\n"
    }
   ]
  }
 ]
}