{
 "title": "MFS i CE Copy",
 "time": { "from": "2025-07-01T06:16:04.523Z", "to": "2025-07-02T06:16:04.523Z" },
 "panels": [
  {
   "title": "MFS por modelo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Model_id,\r\n  ROUND(AVG(Model_Footprint_Score), 4) AS MFS_media\r\nFROM\r\n  `tfm-nttdata.NTTData.metricas`\r\nWHERE\r\n  Model_Footprint_Score IS NOT NULL\r\nGROUP BY\r\n  Model_id\r\nORDER BY\r\n  MFS_media DESC\r\n"
    }
   ]
  },
  {
   "title": "MFS i CE por modelo",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Oficina,\r\n  Model_id,\r\n  CONCAT('Modelo ', CAST(Model_id AS STRING), ' - ', Oficina) AS Etiqueta,\r\n  ROUND(AVG(Carbon_efficiency), 4) AS CE,\r\n  ROUND(AVG(Model_Footprint_Score), 4) AS MFS\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE\r\n  Carbon_efficiency IS NOT NULL\r\n  AND Model_Footprint_Score IS NOT NULL\r\n  AND LOWER(TRIM(Oficina)) != 'desconocido'\r\n  AND TRIM(Oficina) != ''\r\nGROUP BY Oficina, Model_id\r\n"
    }
   ]
  },
  {
   "title": "CE por modelo",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Model_id,\r\n  ROUND(AVG(Carbon_efficiency), 4) AS CE_media\r\nFROM\r\n  `tfm-nttdata.NTTData.metricas`\r\nWHERE\r\n  Carbon_efficiency IS NOT NULL\r\nGROUP BY\r\n  Model_id\r\nORDER BY\r\n  CE_media DESC\r\n"
    }
   ]
  },
  {
   "title": "Modelos con mayor y menor media en indices de sostenibilidad ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 12 },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT *\r\nFROM (\r\n  SELECT\r\n    Model_id,\r\n    ROUND(AVG(Indice_Sostenibilidad), 2) AS Sostenibilidad_media\r\n  FROM `tfm-nttdata.NTTData.metricas`\r\n  WHERE Indice_Sostenibilidad IS NOT NULL\r\n  GROUP BY Model_id\r\n  ORDER BY Sostenibilidad_media DESC\r\n  LIMIT 3\r\n)\r\nUNION ALL\r\nSELECT *\r\nFROM (\r\n  SELECT\r\n    Model_id,\r\n    ROUND(AVG(Indice_Sostenibilidad), 2) AS Sostenibilidad_media\r\n  FROM `tfm-nttdata.NTTData.metricas`\r\n  WHERE Indice_Sostenibilidad IS NOT NULL\r\n  GROUP BY Model_id\r\n  ORDER BY Sostenibilidad_media ASC\r\n  LIMIT 3\r\n)\r\nORDER BY Sostenibilidad_media DESC\r\n"
    }
   ]
  }
 ]
}