{
 "title": "MFS interior",
 "time": { "from": "2024-01-01T00:00:00.000Z", "to": "2025-03-01T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Oficina",
    "label": "Oficina",
    "query": {}
   },
   {
    "name": "Modelo",
    "label": "Modelo",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "MFS por modelo",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Model_id,\r\n  ROUND(AVG(Model_Footprint_Score), 4) AS MFS_media\r\nFROM\r\n  `tfm-nttdata.NTTData.metricas`\r\nWHERE\r\n  Model_Footprint_Score IS NOT NULL \r\n   AND Oficina IN UNNEST([${Oficina}]) \r\nGROUP BY\r\n  Model_id\r\nORDER BY\r\n  MFS_media DESC\r\n"
    }
   ]
  },
  {
   "title": "Media MFS por oficina",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  Oficina,\r\n  AVG(  Model_Footprint_Score) AS MFS\r\nFROM \r\n  `tfm-nttdata.NTTData.metricas`\r\nWHERE\r\n Model_id IN UNNEST([${Modelo:csv}])\r\nGROUP BY\r\n  Oficina\r\nORDER BY\r\n  MFS DESC\r\n"
    }
   ]
  },
  {
   "title": "MFS en el tiempo",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT\r\n  TIMESTAMP(DATE_TRUNC(Execution_day, MONTH)) AS time,\r\n  ROUND(AVG(Model_Footprint_Score), 2) AS model_footprint_score\r\nFROM `tfm-nttdata.NTTData.metricas`\r\nWHERE Execution_day IS NOT NULL\r\n  AND Model_Footprint_Score IS NOT NULL\r\n  AND Model_accuracy < 1\r\n  AND Oficina IN UNNEST([${Oficina}])\r\n  AND Model_id IN UNNEST([${Modelo:csv}])\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  }
 ]
}