{
 "title": "Dashboard inicial",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Oficinas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT COUNT(DISTINCT Oficina)  AS oficinas_activas\r\nFROM `tfm-nttdata.NTTData.metricas`\r\n"
    }
   ]
  },
  {
   "title": "Número de ejecuciones",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT COUNT(Execution_id) FROM `tfm-nttdata.NTTData.metricas` LIMIT 50 "
    }
   ]
  },
  {
   "title": "Modelos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT COUNT(DISTINCT Model_id) AS modelos_activos\r\nFROM `tfm-nttdata.NTTData.metricas`\r\n"
    }
   ]
  },
  {
   "title": "Total de predicciones",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT SUM(Num_predictions) FROM `tfm-nttdata.NTTData.metricas` LIMIT 50 "
    }
   ]
  },
  {
   "title": "Porcentaje de acierto",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT AVG(Model_accuracy) * 100 FROM `tfm-nttdata.NTTData.metricas` LIMIT 50 "
    }
   ]
  },
  {
   "title": "EPT utilizada",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT SUM(EPT_kwh) FROM `tfm-nttdata.NTTData.metricas` LIMIT 50 "
    }
   ]
  },
  {
   "title": "EPP Promedio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT AVG(Epp_wh)  FROM `tfm-nttdata.NTTData.metricas` LIMIT 50 "
    }
   ]
  },
  {
   "title": "Energia de inferencia",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT SUM(Total_inference_energy_wh)/1000 FROM `tfm-nttdata.NTTData.metricas`"
    }
   ]
  },
  {
   "title": "Emisiones totoales",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kg CO2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "tfm-nttdata",
     "rawSql": "SELECT \r\n  SUM(CPT_kg_co2) AS total_emisiones \r\nFROM `tfm-nttdata.NTTData.metricas`\r\n"
    }
   ]
  },
  {
   "title": "Carbon Efficiency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT AVG(Carbon_efficiency) FROM `tfm-nttdata.NTTData.metricas` LIMIT 50 "
    }
   ]
  },
  {
   "title": "Media MFS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NTTData",
     "project": "tfm-nttdata",
     "rawSql": "SELECT AVG(Model_Footprint_Score) FROM `tfm-nttdata.NTTData.metricas` LIMIT 50 "
    }
   ]
  }
 ]
}