name: Test GCP Auth via WIF

on:
  workflow_dispatch:  # ejecutable manualmente

permissions:
  contents: read
  id-token: write  # necesario para usar OIDC con GCP

jobs:
  auth-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Mostrar repo desde variable GitHub
            run: echo "Este es el repo: $GITHUB_REPOSITORY"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GITACTION }}
          service_account: ${{ secrets.SERVICEACCOUNT }}

      - name: Show gcloud info
        run: gcloud info
